### ISSUE TITLE
Add count of snapshots to volume snapshots check.

### ISSUE THREAD

**Issue by riklempens** [infrasonar/netapp-probe#1]
## Request
As a NetApp administrator I would like to know the total number of volume snapshots per volume.

## Why?
The number of snapshot's is limited on a NetApp storage system, if we exceed the limit we would like to setup a condtion.

At the moment we collect the following values:

Metric                | value
----------------------|-------------------------------
name                  | volumename 
Maximum snapshot diff | 7 d
Newest create time    | 2023-02-03 15:05
Oldest create time    | 2023-01-22 00:15
Newest name           | hourly.2023-02-03_1505 
Oldest name           | weekly.2023-01-22_0015

**Comment by joente** [comment]
Added in **v3.0.1**

**Comment by riklempens** [comment]
Snapshot count seems to be incorrect.
It is the same value and not on par with the current monitoring solution.
@Koos85 can you have a look?

**Comment by riklempens** [comment]
This still seems off:
* https://app.infrasonar.com/container/18184/asset/18232/collector/7047
* https://oversig.ht/#/c/46/e/ce28fc838ad8/h/ce28fc838ad8-2d4d35e858b5/probes/netappprobe

**Comment by riklempens** [comment]
Closing this issue as the metric was already available in the volume check.
