### ISSUE TITLE
`Lag time` and `Transfer total duration` show weird values

### ISSUE THREAD

**Issue by riklempens** [infrasonar/netapp-probe#2]
Check: `NetApp` \ `SnapMirror` \ `SnapMirror`

Items `Lag time` and `Transfer total duration` are shown in a not human/machine readable format.

One of our checks results show:

Lag time: `PT4M9S`
Transfer total duration: `PT24S`

We should somehow convert this to seconds.

**Comment by joente** [comment]
Fixed in **v3.0.1**

**Comment by riklempens** [comment]
The snapshot `Transfer end time` seems to be the date we take the sample.
I will first figure out the setup with the customer so we know what to look for.

**Comment by riklempens** [comment]
Closing this issue as it is solved.
